# Generated by Django 5.0 on 2023-12-30 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookListDRF', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='inventory',
        ),
    ]
